<?php $last_modified = "Apr 16, 2012 11:15 pm"; ?>

<p>In informatica, le Active Server Pages (Pagine Server Attive, in genere abbreviato in ASP) sono pagine web contenenti, oltre al puro codice HTML, degli script che verranno eseguiti dal server per generare runtime il codice HTML da inviare al browser dell'utente (proprio per questo vengono in genere definite pagine web dinamiche).In questo modo è possibile mostrare contenuti dinamici (ad esempio estratti da database che risiedono sul server web) e modificarne l'aspetto secondo le regole programmate negli script, il tutto senza dover inviare il codice del programma all'utente finale (al quale va inviato solo il risultato), con un notevole risparmio di tempi e banda.</p>

<p>I linguaggi utilizzati sono VBScript e JScript per l'ambiente ASP e VB.NET, C# e J# per l'ambiente ASP.NET (anche se il più utilizzato è proprio VB.NET). Grazie a questi linguaggi il sistema dinamico può comunicare lato server con tutti gli oggetti presenti sul sistema, infatti le possibilità offerte dal sistema sono fortemente orientate verso l'interfaccia con un corrispondente database, rendendo così possibile lo sviluppo di siti dinamici basati sulle informazioni contenute nel database. È possibile interfacciare le pagine ASP con qualsiasi tipo di database che abbia un driver OLE-db o ODBC, come ad esempio Access, SQL Server, MySQL, Oracle, Firebird, Sybase e tanti altri.</p>

<p>Funziona ufficialmente solo sul web server Microsoft Internet Information Services (IIS). Nonostante questo, per quanti utilizzano piattaforme GNU/Linux è disponibile un emulatore che consente di eseguire i codici ASP senza dover riscrivere l'intero progetto ma soltanto una piccola porzione di esso. Nel diffuso web server Apache, ad esempio, è possibile utilizzare pagine dalla sintassi simile ad ASP installando e configurando il modulo Apache: ASP funzionante sulla base di Perl. In alternativa esiste inoltre un modulo generalmente noto come ChiliASP (su cui si basa il modulo SJSASP, Sun Java System Active Server Pages, disponibile sul sito di SUN).</p>

<p>Una caratteristica molto apprezzata dagli utilizzatori dell'interprete ASP è la semplice e comprensibile sintassi di programmazione che rende la curva di apprendimento di tale linguaggio poco ripida. L'interprete ASP, tuttavia, presenta alcuni limiti, specialmente di prestazioni. </p>

<p>Principali concorrenti di ASP sono il PHP, che funziona in modo molto simile, ma con una sintassi del tutto diversa dal VBScript, e l'unione di Perl/Python e CGI, che è un meccanismo meno integrato nella sola pagina web e quindi più macchinoso da gestire, che tuttavia permette al programmatore più flessibilità.</p>

<p>ASP è stato ufficialmente abbandonato, seppure continua ancora ad essere supportato e può funzionare sulle ultime versioni di IIS, in favore di ASP.NET, ormai giunto alla versione 4.0, che consente di creare applicazioni web su piattaforma Microsoft che possono sfruttare anche funzionalità avanzate e, soprattutto, contare su un'infrastruttura molto più avanzata, qual è quella offerta dal .NET Framework in accoppiata con IIS 7.</p>